hash-format = "sha256"

[[files]]
file = "config/appliedenergistics2/client.json"

[[files]]
file = "config/appliedenergistics2/common.json"

[[files]]
file = "config/boringbackgrounds.json"

[[files]]
file = "config/carrier.json"

[[files]]
file = "config/dark-loading-screen.json"

[[files]]
file = "config/expandedstorage.json"

[[files]]
file = "config/fpsreducer.json"

[[files]]
file = "config/ftbquests/quests/chapter_groups.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/1st_industrial_revolution.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/2nd_industrial_revolution.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/3rd_industrial_revolution.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/adventure.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/better_storage.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/collectors_quest.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/conjuring.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/deeply_learning_mobs.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/how_to_become_a_witcj.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/spectrum.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/survival_basics.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/tech.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/technologys_rebirth__part_ii.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/technologys_reborn.snbt"

[[files]]
file = "config/ftbquests/quests/data.snbt"

[[files]]
file = "config/ftbquests/quests/reward_tables/plantchoice.snbt"

[[files]]
file = "config/ftbquests/quests/reward_tables/pristine_matter.snbt"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/seasons.json"

[[files]]
file = "config/sidebar_buttons.json"

[[files]]
file = "config/slightguimodifications/buttons.png"

[[files]]
file = "config/slightguimodifications/config.json5"

[[files]]
file = "config/slightguimodifications/cts.groovy"

[[files]]
file = "config/slightguimodifications/discord_button.png"

[[files]]
file = "config/slightguimodifications/discord_button_hovered.png"

[[files]]
file = "config/slightguimodifications/slider.png"

[[files]]
file = "config/slightguimodifications/slider_hovered.png"

[[files]]
file = "config/slightguimodifications/text_field.png"

[[files]]
file = "kubejs/assets/authme/textures/gui/widgets.png"

[[files]]
file = "kubejs/assets/indrev/lang/en_us.json"

[[files]]
file = "kubejs/assets/indrev/lang/pt_br.json"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_0.png"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_1.png"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_2.png"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_3.png"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_4.png"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/background/panorama_5.png"

[[files]]
file = "kubejs/assets/minecraft/textures/gui/title/minecraft.png"

[[files]]
file = "kubejs/client_scripts/rei_unification.js"

[[files]]
file = "kubejs/config/client.properties"

[[files]]
file = "kubejs/config/common.properties"

[[files]]
file = "kubejs/server_scripts/recipetypes/indrev/infuse.js"

[[files]]
file = "kubejs/server_scripts/recipetypes/indrev/pulverize.js"

[[files]]
file = "kubejs/server_scripts/recipetypes/minecraft/shaped.js"

[[files]]
file = "kubejs/server_scripts/recipetypes/minecraft/shaped.js.bak"

[[files]]
file = "kubejs/server_scripts/recipetypes/techreborn/chemical_reactor.js"

[[files]]
file = "kubejs/server_scripts/tags.js"

[[files]]
file = "kubejs/server_scripts/unification/materials.js"

[[files]]
file = "mods/advancements-enlarger.toml"
metafile = true

[[files]]
file = "mods/ae2things.toml"
metafile = true

[[files]]
file = "mods/appleskin.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2.toml"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
metafile = true

[[files]]
file = "mods/artifacts-fabric.toml"
metafile = true

[[files]]
file = "mods/attributefix.toml"
metafile = true

[[files]]
file = "mods/auth-me.toml"
metafile = true

[[files]]
file = "mods/auto-config-updated-api.toml"
metafile = true

[[files]]
file = "mods/autoclick-machine.toml"
metafile = true

[[files]]
file = "mods/balm-fabric.toml"
metafile = true

[[files]]
file = "mods/basic-aiots.toml"
metafile = true

[[files]]
file = "mods/betterloadingscreen.toml"
metafile = true

[[files]]
file = "mods/blockus.toml"
metafile = true

[[files]]
file = "mods/boring-backgrounds.toml"
metafile = true

[[files]]
file = "mods/break-progress.toml"
metafile = true

[[files]]
file = "mods/can-i-mine-this-block.toml"
metafile = true

[[files]]
file = "mods/can-you-trash-it.toml"
metafile = true

[[files]]
file = "mods/carrier.toml"
metafile = true

[[files]]
file = "mods/cc-restitched.toml"
metafile = true

[[files]]
file = "mods/cherished-worlds-fabric.toml"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
metafile = true

[[files]]
file = "mods/clumps.toml"
metafile = true

[[files]]
file = "mods/conjuring.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-fabric.toml"
metafile = true

[[files]]
file = "mods/coxinha-utilities.toml"
metafile = true

[[files]]
file = "mods/crafting-tweaks-fabric.toml"
metafile = true

[[files]]
file = "mods/croptopia-fabric.toml"
metafile = true

[[files]]
file = "mods/croptosis.toml"
metafile = true

[[files]]
file = "mods/dank-storage-fabric.toml"
metafile = true

[[files]]
file = "mods/dark-loading-screen.toml"
metafile = true

[[files]]
file = "mods/deep-mob-learning-refabricated.toml"
metafile = true

[[files]]
file = "mods/deep-mob-learning-simulacrum.toml"
metafile = true

[[files]]
file = "mods/diggus-maximus.toml"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.toml"
metafile = true

[[files]]
file = "mods/expanded-storage-fabric.toml"
metafile = true

[[files]]
file = "mods/extra-generators.toml"
metafile = true

[[files]]
file = "mods/ezpas.toml"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
metafile = true

[[files]]
file = "mods/fabric-disable-custom-worlds-advice.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons.toml"
metafile = true

[[files]]
file = "mods/fabric-waystones.toml"
metafile = true

[[files]]
file = "mods/feature-nbt-deadlock-be-gone.toml"
metafile = true

[[files]]
file = "mods/fps-reducer.toml"
metafile = true

[[files]]
file = "mods/ftb-chunks-fabric.toml"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.toml"
metafile = true

[[files]]
file = "mods/ftb-quests-fabric.toml"
metafile = true

[[files]]
file = "mods/ftb-teams-fabric.toml"
metafile = true

[[files]]
file = "mods/glassential-fabric.toml"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.toml"
metafile = true

[[files]]
file = "mods/incantationem.toml"
metafile = true

[[files]]
file = "mods/indium.toml"
metafile = true

[[files]]
file = "mods/industrial-revolution.toml"
metafile = true

[[files]]
file = "mods/inmis.toml"
metafile = true

[[files]]
file = "mods/inventory-hud-forge.toml"
metafile = true

[[files]]
file = "mods/inventory-sorting.toml"
metafile = true

[[files]]
file = "mods/iron-furnaces-fabric.toml"
metafile = true

[[files]]
file = "mods/iron-jetpacks-fabric.toml"
metafile = true

[[files]]
file = "mods/item-filters-fabric.toml"
metafile = true

[[files]]
file = "mods/jumpoverfences.toml"
metafile = true

[[files]]
file = "mods/kibe.toml"
metafile = true

[[files]]
file = "mods/kubejs-extras.toml"
metafile = true

[[files]]
file = "mods/kubejs-fabric.toml"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
metafile = true

[[files]]
file = "mods/lifts.toml"
metafile = true

[[files]]
file = "mods/light-overlay.toml"
metafile = true

[[files]]
file = "mods/lithium.toml"
metafile = true

[[files]]
file = "mods/megane.toml"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.toml"
metafile = true

[[files]]
file = "mods/mo-structures.toml"
metafile = true

[[files]]
file = "mods/modern-industrialization.toml"
metafile = true

[[files]]
file = "mods/modmenu.toml"
metafile = true

[[files]]
file = "mods/mouse-wheelie.toml"
metafile = true

[[files]]
file = "mods/ninjaphenixs-container-library.toml"
metafile = true

[[files]]
file = "mods/no-null-processors.toml"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
metafile = true

[[files]]
file = "mods/onastick.toml"
metafile = true

[[files]]
file = "mods/owo-lib.toml"
metafile = true

[[files]]
file = "mods/patchouli-fabric.toml"
metafile = true

[[files]]
file = "mods/pehkui.toml"
metafile = true

[[files]]
file = "mods/phosphor.toml"
metafile = true

[[files]]
file = "mods/pling.toml"
metafile = true

[[files]]
file = "mods/quarry-reborn.toml"
metafile = true

[[files]]
file = "mods/reborncore.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.toml"
metafile = true

[[files]]
file = "mods/rhino.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest-fabric.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-resources.toml"
metafile = true

[[files]]
file = "mods/secret-rooms-fabric.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.toml"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
metafile = true

[[files]]
file = "mods/slotlink.toml"
metafile = true

[[files]]
file = "mods/slotlock.toml"
metafile = true

[[files]]
file = "mods/smoother-bedrock.toml"
metafile = true

[[files]]
file = "mods/sodium.toml"
metafile = true

[[files]]
file = "mods/spatial-harvesters-fabric.toml"
metafile = true

[[files]]
file = "mods/spectrum.toml"
metafile = true

[[files]]
file = "mods/staff-of-building.toml"
metafile = true

[[files]]
file = "mods/stoneholm.toml"
metafile = true

[[files]]
file = "mods/structure-tools.toml"
metafile = true

[[files]]
file = "mods/techreborn.toml"
metafile = true

[[files]]
file = "mods/terrarian-slimes.toml"
metafile = true

[[files]]
file = "mods/textile-backup.toml"
metafile = true

[[files]]
file = "mods/time-in-a-bottle.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
metafile = true

[[files]]
file = "mods/trap-expansion-fabric.toml"
metafile = true

[[files]]
file = "mods/trashslot-fabric-edition.toml"
metafile = true

[[files]]
file = "mods/trinkets-fabric.toml"
metafile = true

[[files]]
file = "mods/vanilla-excavators.toml"
metafile = true

[[files]]
file = "mods/vanilla-hammers.toml"
metafile = true

[[files]]
file = "mods/wireless-networks.toml"
metafile = true

[[files]]
file = "mods/wmitaf.toml"
metafile = true

[[files]]
file = "mods/wthit.toml"
metafile = true

[[files]]
file = "mods/yosbr.toml"
metafile = true

[[files]]
file = "mods/youre-in-grave-danger.toml"
metafile = true
