name = "Can You Trash It?"
filename = "cyti-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3598/312/cyti-1.0.3.jar"
hash-format = "murmur2"
hash = "1793312566"

[update]
[update.curseforge]
file-id = 3598312
project-id = 564152
