name = "Dank Storage Fabric"
filename = "dankstorage-1.18.1-3.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/425/dankstorage-1.18.1-3.5.2.jar"
hash-format = "murmur2"
hash = "2901325637"

[update]
[update.curseforge]
file-id = 3638425
project-id = 400619
