name = "Glassential (Fabric)"
filename = "glassential-fabric-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3532/14/glassential-fabric-1.3.0.jar"
hash-format = "murmur2"
hash = "3442479726"

[update]
[update.curseforge]
file-id = 3532014
project-id = 320778
