name = "Incantationem"
filename = "incantationem-1.1.3+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3571/914/incantationem-1.1.3+1.18.1.jar"
hash-format = "murmur2"
hash = "2653177041"

[update]
[update.curseforge]
file-id = 3571914
project-id = 483166
