name = "Tech Reborn"
filename = "TechReborn-5.1.0-beta.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/223/TechReborn-5.1.0-beta.5.jar"
hash-format = "murmur2"
hash = "2631316323"

[update]
[update.curseforge]
file-id = 3597223
project-id = 233564
