name = "WMITAF"
filename = "wmitaf-fabric-mc1.18.1-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/721/wmitaf-fabric-mc1.18.1-2.2.0.jar"
hash-format = "murmur2"
hash = "2010666834"

[update]
[update.curseforge]
file-id = 3566721
project-id = 547358
